### PR TITLE
Fix vendor image mismatch

### PR DESCRIPTION
**Pull request by ripee**
Users have confirmed that this works. @underscoremone @micky387

### CODE REVIEW

**Comment by underscoremone** [comment]
Good catch!

tbh I would prefer that the changes regarding the vendor part were included amending the previous commit (https://github.com/samsung-apq8084/android_device_samsung_tblte/commit/9216ba7cb36d561dc0e347fbf42a13ff19fbf543) because that commit was wrongly implemented by miky387 and we should fix that.
Not sure why you removed tblte (you probably just followed the Note4 variants), I'm not familiar with the Note Edge but seems that N915F (tblte) and N915FY (tbltexx) are two different variants.. so we probably don't want to remove it.. miky387 probably knows better.

As this is miky387's tree, I'm adding him as reviewer and I'll leave the decision to him.

Thank you for the help. Keep it up.

**Comment by micky387** [comment]
Hi. sorry for my absence but I have to deal with a lack of staff right now, so I have no lot of free time ..

Good catch @ripee ,I am an idiot. 
But you must keep tblte. 
Note Edge are slightly different with Note 4 with bootloader.
There are tblte (international) and tbltexx (in fact ro.product.name", "tbltebtu) for European

I have a problem with the bootloader to distinguish between N915F and N915FY (slightly explains here)  
https://github.com/samsung-apq8084/android_device_samsung_tblte/commit/f5d33bff6d83ef60012b5fbadc80b156f9b821ae#diff-f1b39e7f4f70b876e89ba6b3b5ff7e18

All the time, tbltebtu (tbltexx) are recognized as SM-N915F before this commit.

So juste restore tblte variants and it's ok for me.
Thanks guys

**Comment by micky387** [comment]
Closed. I have amending the previous commit.
thanks @ripee

**Comment by ripee** [comment]
Ya, I did just copy over from trlte. Wasn't too sure about N915F vs. N915FY. But I'm glad the fix is relatively easy ;)

**Pull request closed without merging**
